/**
 * Generates supabase/seed.sql from the demo builder in @sagolik/core, so the
 * Supabase and in-memory demo environments are identical.
 *
 * Every timestamp/date is shifted by (now() − ANCHOR) at seed time, so the
 * demo stays "live" whenever you run `supabase db reset`.
 *
 *   pnpm gen:seed
 */
import { writeFileSync } from "node:fs";
import { LOCAL_ENCRYPTION_KEYS } from "../packages/config/src/env";
import { buildDemoData, DEMO_PASSWORD, DEMO_PERSONAS, SEED_ORDER } from "../packages/core/src/demo/seed";
import { toSnake } from "../packages/database/src/case";
import { parseKeyRing } from "../packages/security/src/crypto";

const ANCHOR = "2026-09-22T12:00:00.000Z";
const TS = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/;
const DATE = /^\d{4}-\d{2}-\d{2}$/;

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

function literal(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  if (typeof v === "string") {
    if (TS.test(v)) return `(${q(v)}::timestamptz + (select shift from _seed_shift))`;
    if (DATE.test(v)) return `(${q(v)}::date + (select days from _seed_shift))`;
    return q(v);
  }
  if (Array.isArray(v)) {
    if (v.some((x) => x !== null && typeof x === "object")) return `${q(JSON.stringify(v))}::jsonb`;
    return q(`{${v.map((x) => `"${String(x).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`).join(",")}}`);
  }
  return `${q(JSON.stringify(v))}::jsonb`;
}

const data = buildDemoData(new Date(ANCHOR), parseKeyRing(LOCAL_ENCRYPTION_KEYS));
const out: string[] = [
  "-- =============================================================================",
  "-- GENERATED by `pnpm gen:seed` from packages/core/src/demo/seed.ts — do not edit.",
  "-- LOCAL DEVELOPMENT ONLY. Fictional people, companies and properties.",
  `-- Demo sign-in: any persona email below, password "${DEMO_PASSWORD}".`,
  "-- Encrypted demo values use the LOCAL development key (see .env.example).",
  "-- =============================================================================",
  "",
  "create temporary table _seed_shift as",
  `  select now() - ${q(ANCHOR)}::timestamptz as shift,`,
  `         (current_date - (${q(ANCHOR)}::timestamptz)::date) as days;`,
  "",
  "-- Auth users (Supabase GoTrue). Passwords are bcrypt-hashed here; never ship this to production.",
];
for (const p of DEMO_PERSONAS) {
  out.push(
    `insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, email_change, email_change_token_new, recovery_token)`,
    `values ('00000000-0000-0000-0000-000000000000', ${q(p.userId)}, 'authenticated', 'authenticated', ${q(p.email)}, crypt(${q(DEMO_PASSWORD)}, gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', ${q(JSON.stringify({ full_name: p.name }))}, now(), now(), '', '', '', '');`,
    `insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)`,
    `values (${q(p.userId)}, ${q(p.userId)}, ${q(p.userId)}, ${q(JSON.stringify({ sub: p.userId, email: p.email }))}::jsonb, 'email', now(), now(), now());`,
  );
}
out.push("");

for (const table of SEED_ORDER) {
  const rows = data.rows[table] as Array<Record<string, unknown>> | undefined;
  if (!rows?.length) continue;
  const cols = Object.keys(rows[0]!);
  out.push(`-- ${table}`, `insert into public.${table} (${cols.map(toSnake).join(", ")}) values`);
  out.push(rows.map((r) => `  (${cols.map((c) => literal(r[c])).join(", ")})`).join(",\n") + ";", "");
}
out.push("drop table _seed_shift;", "");

const target = new URL("../supabase/seed.sql", import.meta.url);
writeFileSync(target, out.join("\n"));
console.log(`wrote ${target.pathname} (${out.length} lines). Demo files for the vault: run \`pnpm seed:storage\` against a Supabase project.`);
