-- =============================================================================
-- GENERATED FILE — do not edit by hand.
-- Source: packages/auth (role matrix) and packages/workflow (state machine).
-- Regenerate with `pnpm gen:sql`; the schema-parity test enforces it.
-- =============================================================================

create table if not exists public.role_permissions (
  role public.participant_role not null,
  permission text not null,
  primary key (role, permission)
);

create table if not exists public.organization_role_permissions (
  role public.organization_role not null references public.organization_roles (key),
  permission text not null,
  primary key (role, permission)
);

insert into public.organization_roles (key, description) values
  ('organization_admin', 'Manages the organization, its members and its transactions'),
  ('member', 'Works on transactions they are invited to'),
  ('auditor', 'Read-only access to the organization''s transactions and audit trail');

insert into public.role_permissions (role, permission) values
  ('buyer', 'document.upload'),
  ('buyer', 'document.view'),
  ('buyer', 'financial.view'),
  ('buyer', 'message.send'),
  ('buyer', 'payment.initiate'),
  ('buyer', 'signature.sign'),
  ('buyer', 'task.complete_own'),
  ('buyer', 'transaction.view'),
  ('co_buyer', 'document.upload'),
  ('co_buyer', 'document.view'),
  ('co_buyer', 'financial.view'),
  ('co_buyer', 'message.send'),
  ('co_buyer', 'payment.initiate'),
  ('co_buyer', 'signature.sign'),
  ('co_buyer', 'task.complete_own'),
  ('co_buyer', 'transaction.view'),
  ('seller', 'document.upload'),
  ('seller', 'document.view'),
  ('seller', 'financial.view'),
  ('seller', 'message.send'),
  ('seller', 'signature.sign'),
  ('seller', 'task.complete_own'),
  ('seller', 'transaction.view'),
  ('co_seller', 'document.upload'),
  ('co_seller', 'document.view'),
  ('co_seller', 'financial.view'),
  ('co_seller', 'message.send'),
  ('co_seller', 'signature.sign'),
  ('co_seller', 'task.complete_own'),
  ('co_seller', 'transaction.view'),
  ('agent', 'document.approve'),
  ('agent', 'document.upload'),
  ('agent', 'document.view'),
  ('agent', 'message.send'),
  ('agent', 'participant.invite'),
  ('agent', 'signature.request'),
  ('agent', 'task.complete_own'),
  ('agent', 'task.manage'),
  ('agent', 'transaction.edit'),
  ('agent', 'transaction.view'),
  ('buyer_agent', 'document.approve'),
  ('buyer_agent', 'document.upload'),
  ('buyer_agent', 'document.view'),
  ('buyer_agent', 'message.send'),
  ('buyer_agent', 'participant.invite'),
  ('buyer_agent', 'signature.request'),
  ('buyer_agent', 'task.complete_own'),
  ('buyer_agent', 'task.manage'),
  ('buyer_agent', 'transaction.edit'),
  ('buyer_agent', 'transaction.view'),
  ('seller_agent', 'document.approve'),
  ('seller_agent', 'document.upload'),
  ('seller_agent', 'document.view'),
  ('seller_agent', 'message.send'),
  ('seller_agent', 'participant.invite'),
  ('seller_agent', 'signature.request'),
  ('seller_agent', 'task.complete_own'),
  ('seller_agent', 'task.manage'),
  ('seller_agent', 'transaction.edit'),
  ('seller_agent', 'transaction.view'),
  ('broker', 'audit.view'),
  ('broker', 'document.approve'),
  ('broker', 'document.upload'),
  ('broker', 'document.view'),
  ('broker', 'message.send'),
  ('broker', 'participant.invite'),
  ('broker', 'signature.request'),
  ('broker', 'task.complete_own'),
  ('broker', 'task.manage'),
  ('broker', 'transaction.edit'),
  ('broker', 'transaction.view'),
  ('loan_officer', 'document.upload'),
  ('loan_officer', 'document.view'),
  ('loan_officer', 'financial.view'),
  ('loan_officer', 'message.send'),
  ('loan_officer', 'milestone.approve'),
  ('loan_officer', 'mortgage.update'),
  ('loan_officer', 'signature.request'),
  ('loan_officer', 'task.complete_own'),
  ('loan_officer', 'transaction.view'),
  ('mortgage_processor', 'document.upload'),
  ('mortgage_processor', 'document.view'),
  ('mortgage_processor', 'financial.view'),
  ('mortgage_processor', 'message.send'),
  ('mortgage_processor', 'mortgage.update'),
  ('mortgage_processor', 'signature.request'),
  ('mortgage_processor', 'task.complete_own'),
  ('mortgage_processor', 'transaction.view'),
  ('title_officer', 'audit.view'),
  ('title_officer', 'beneficiary.verify'),
  ('title_officer', 'document.approve'),
  ('title_officer', 'document.upload'),
  ('title_officer', 'document.view'),
  ('title_officer', 'document.view_restricted'),
  ('title_officer', 'financial.view'),
  ('title_officer', 'identity.view_result'),
  ('title_officer', 'message.send'),
  ('title_officer', 'milestone.approve'),
  ('title_officer', 'recording.confirm'),
  ('title_officer', 'recording.submit'),
  ('title_officer', 'signature.request'),
  ('title_officer', 'task.complete_own'),
  ('title_officer', 'task.manage'),
  ('title_officer', 'title.update'),
  ('title_officer', 'transaction.close'),
  ('title_officer', 'transaction.transition'),
  ('title_officer', 'transaction.view'),
  ('escrow_officer', 'audit.view'),
  ('escrow_officer', 'beneficiary.modify'),
  ('escrow_officer', 'beneficiary.verify'),
  ('escrow_officer', 'compliance.review'),
  ('escrow_officer', 'document.approve'),
  ('escrow_officer', 'document.upload'),
  ('escrow_officer', 'document.view'),
  ('escrow_officer', 'document.view_restricted'),
  ('escrow_officer', 'escrow.manage'),
  ('escrow_officer', 'financial.view'),
  ('escrow_officer', 'identity.view_result'),
  ('escrow_officer', 'message.send'),
  ('escrow_officer', 'milestone.approve'),
  ('escrow_officer', 'payment.approve'),
  ('escrow_officer', 'signature.request'),
  ('escrow_officer', 'task.complete_own'),
  ('escrow_officer', 'task.manage'),
  ('escrow_officer', 'transaction.close'),
  ('escrow_officer', 'transaction.transition'),
  ('escrow_officer', 'transaction.view'),
  ('attorney', 'audit.view'),
  ('attorney', 'compliance.review'),
  ('attorney', 'document.approve'),
  ('attorney', 'document.upload'),
  ('attorney', 'document.view'),
  ('attorney', 'document.view_restricted'),
  ('attorney', 'financial.view'),
  ('attorney', 'identity.view_result'),
  ('attorney', 'message.send'),
  ('attorney', 'milestone.approve'),
  ('attorney', 'recording.confirm'),
  ('attorney', 'recording.submit'),
  ('attorney', 'signature.request'),
  ('attorney', 'task.complete_own'),
  ('attorney', 'transaction.close'),
  ('attorney', 'transaction.transition'),
  ('attorney', 'transaction.view'),
  ('notary', 'document.view'),
  ('notary', 'message.send'),
  ('notary', 'task.complete_own'),
  ('notary', 'transaction.view'),
  ('insurance_agent', 'document.upload'),
  ('insurance_agent', 'document.view'),
  ('insurance_agent', 'message.send'),
  ('insurance_agent', 'task.complete_own'),
  ('insurance_agent', 'transaction.view'),
  ('transaction_coordinator', 'audit.view'),
  ('transaction_coordinator', 'document.approve'),
  ('transaction_coordinator', 'document.upload'),
  ('transaction_coordinator', 'document.view'),
  ('transaction_coordinator', 'financial.view'),
  ('transaction_coordinator', 'message.send'),
  ('transaction_coordinator', 'milestone.approve'),
  ('transaction_coordinator', 'participant.invite'),
  ('transaction_coordinator', 'participant.remove'),
  ('transaction_coordinator', 'signature.request'),
  ('transaction_coordinator', 'task.complete_own'),
  ('transaction_coordinator', 'task.manage'),
  ('transaction_coordinator', 'transaction.edit'),
  ('transaction_coordinator', 'transaction.transition'),
  ('transaction_coordinator', 'transaction.view'),
  ('auditor', 'audit.export'),
  ('auditor', 'audit.view'),
  ('auditor', 'document.view'),
  ('auditor', 'document.view_restricted'),
  ('auditor', 'financial.view'),
  ('auditor', 'identity.view_result'),
  ('auditor', 'transaction.view'),
  ('accountant', 'document.upload'),
  ('accountant', 'document.view'),
  ('accountant', 'message.send'),
  ('accountant', 'task.complete_own'),
  ('accountant', 'transaction.view');

insert into public.organization_role_permissions (role, permission) values
  ('organization_admin', 'audit.export'),
  ('organization_admin', 'audit.view'),
  ('organization_admin', 'compliance.review'),
  ('organization_admin', 'document.view'),
  ('organization_admin', 'participant.invite'),
  ('organization_admin', 'participant.remove'),
  ('organization_admin', 'task.manage'),
  ('organization_admin', 'transaction.edit'),
  ('organization_admin', 'transaction.transition'),
  ('organization_admin', 'transaction.view'),
  ('auditor', 'audit.export'),
  ('auditor', 'audit.view'),
  ('auditor', 'document.view'),
  ('auditor', 'document.view_restricted'),
  ('auditor', 'financial.view'),
  ('auditor', 'transaction.view');

insert into public.transaction_states (key, label, sort_order, is_terminal) values
  ('draft', 'Draft', 0, false),
  ('invited', 'Parties invited', 1, false),
  ('identity_pending', 'Verifying identities', 2, false),
  ('documents_pending', 'Collecting documents', 3, false),
  ('financing_pending', 'Financing', 4, false),
  ('conditions_pending', 'Clearing conditions', 5, false),
  ('ready_for_signing', 'Ready for signing', 6, false),
  ('signing', 'Signing', 7, false),
  ('escrow_pending', 'Funding escrow', 8, false),
  ('funding_pending', 'Lender funding', 9, false),
  ('recording_pending', 'Recording', 10, false),
  ('ownership_transfer', 'Ownership transferred', 11, false),
  ('closed', 'Closed', 12, true),
  ('cancelled', 'Cancelled', 113, true),
  ('disputed', 'Disputed', 114, false);

insert into public.transaction_transitions (from_state, to_state, permission, automatic) values
  ('draft', 'invited', 'transaction.transition', false),
  ('invited', 'identity_pending', 'transaction.transition', false),
  ('identity_pending', 'documents_pending', 'transaction.transition', true),
  ('documents_pending', 'financing_pending', 'transaction.transition', true),
  ('financing_pending', 'conditions_pending', 'transaction.transition', true),
  ('conditions_pending', 'ready_for_signing', 'transaction.transition', true),
  ('ready_for_signing', 'signing', 'transaction.transition', false),
  ('signing', 'escrow_pending', 'transaction.transition', true),
  ('escrow_pending', 'funding_pending', 'transaction.transition', true),
  ('funding_pending', 'recording_pending', 'transaction.transition', true),
  ('recording_pending', 'ownership_transfer', 'transaction.transition', true),
  ('ownership_transfer', 'closed', 'transaction.close', false),
  ('ready_for_signing', 'conditions_pending', 'transaction.transition', false),
  ('signing', 'conditions_pending', 'transaction.transition', false),
  ('escrow_pending', 'signing', 'transaction.transition', false),
  ('funding_pending', 'escrow_pending', 'transaction.transition', false),
  ('recording_pending', 'funding_pending', 'transaction.transition', false),
  ('draft', 'cancelled', 'transaction.close', false),
  ('draft', 'disputed', 'transaction.view', false),
  ('invited', 'cancelled', 'transaction.close', false),
  ('invited', 'disputed', 'transaction.view', false),
  ('identity_pending', 'cancelled', 'transaction.close', false),
  ('identity_pending', 'disputed', 'transaction.view', false),
  ('documents_pending', 'cancelled', 'transaction.close', false),
  ('documents_pending', 'disputed', 'transaction.view', false),
  ('financing_pending', 'cancelled', 'transaction.close', false),
  ('financing_pending', 'disputed', 'transaction.view', false),
  ('conditions_pending', 'cancelled', 'transaction.close', false),
  ('conditions_pending', 'disputed', 'transaction.view', false),
  ('ready_for_signing', 'cancelled', 'transaction.close', false),
  ('ready_for_signing', 'disputed', 'transaction.view', false),
  ('signing', 'cancelled', 'transaction.close', false),
  ('signing', 'disputed', 'transaction.view', false),
  ('escrow_pending', 'cancelled', 'transaction.close', false),
  ('escrow_pending', 'disputed', 'transaction.view', false),
  ('funding_pending', 'cancelled', 'transaction.close', false),
  ('funding_pending', 'disputed', 'transaction.view', false),
  ('recording_pending', 'cancelled', 'transaction.close', false),
  ('recording_pending', 'disputed', 'transaction.view', false),
  ('ownership_transfer', 'cancelled', 'transaction.close', false),
  ('ownership_transfer', 'disputed', 'transaction.view', false),
  ('disputed', 'draft', 'transaction.transition', false),
  ('disputed', 'invited', 'transaction.transition', false),
  ('disputed', 'identity_pending', 'transaction.transition', false),
  ('disputed', 'documents_pending', 'transaction.transition', false),
  ('disputed', 'financing_pending', 'transaction.transition', false),
  ('disputed', 'conditions_pending', 'transaction.transition', false),
  ('disputed', 'ready_for_signing', 'transaction.transition', false),
  ('disputed', 'signing', 'transaction.transition', false),
  ('disputed', 'escrow_pending', 'transaction.transition', false),
  ('disputed', 'funding_pending', 'transaction.transition', false),
  ('disputed', 'recording_pending', 'transaction.transition', false),
  ('disputed', 'ownership_transfer', 'transaction.transition', false),
  ('disputed', 'cancelled', 'transaction.close', false);
